### ISSUE TITLE
Not able to register my Openstack Newton as VIM in Openbaton using Keystone V3 APIs

### ISSUE THREAD

**Issue by ashish235** [openbaton/openstack4j-plugin#14]
Not able to add Openstack as VIM. Getting this error in logs. 

[pool-1-thread-3] INFO org.openbaton.drivers.openstack4j.OpenStack4JDriver -
Waiting for RPC requests
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Received message
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - There are 1 parameters
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Looking for method: listImages
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Domain id: Default
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Project id: 4222986cef724b489a74344bb454a274
[pool-1-thread-3] DEBUG org.openstack4j.core.transport.internal.HttpExecutor - Executing Request: http://172.16.110.254:5000/v3 -> /auth/tokens
[pool-1-thread-3] ERROR org.openbaton.drivers.openstack4j.OpenStack4JDriver - null
java.lang.NullPointerException
        at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:116)
        at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listImages(OpenStack4JDriver.java:331)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openbaton.plugin.PluginListener.executeMethod(PluginListener.java:208)
        at org.openbaton.plugin.PluginListener.run(PluginListener.java:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[pool-1-thread-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Answer is: {
  "exception": {
    "stackTrace": [],
    "suppressedExceptions": []
  }
}
[pool-1-threAD-3] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Reply queue is: amq.gen-nzaa9DLNvEHAdQFNEq-JFA

**Comment by ashish235** [comment]
Team, 

Can someone please look into the issue? I did try with various combinations to make it work with keystone v3 API but it's just not working. 

If someone can help me with the sample configuration file to register PoP. The ones from the Readme page of this project doesn't work.

**Comment by gc4rella** [comment]
it is now supported since release 4. please look at the docs: http://openbaton.github.io/documentation/pop-openstack/
