### ISSUE TITLE
VimDriverException: Multiple possible networks found, use a Network ID to be more specific.

### ISSUE THREAD

**Issue by dtyunin** [openbaton/openstack4j-plugin#19]
Hello, guys. I'm trying to launch iPerf test scenario as mentioned in tutorial [here](http://openbaton.github.io/documentation/iperf-NSR/)
I was able to:
1. Run ubuntu14.04 instance in our Openstack lab (We have Openstack Newton installed)
![openstack_version_lublin](https://cloud.githubusercontent.com/assets/19220793/24547960/34f4fa62-161b-11e7-95a5-89a53fd89e2c.png)

2. Run Openbaton docker standalone version with such commands
`sudo docker pull openbaton/standalone`
`sudo docker run --name openbaton -d -h openbaton-rabbitmq -p 8080:8080 -p 5672:5672 -p 15672:15672 -p 8443:8443 -e RABBITMQ_BROKERIP=<RabbitMQ IP> openbaton/standalone`
3. Add Openstack PoP.
4. Load iperf-client and iperf-server VNF packages
<details>
  <summary>iperf-client</summary>
  <p>

  ```JSON
{
  "name":"iperf-client",
  "vendor":"FOKUS",
  "version":"1.0",
  "lifecycle_event":[
    {
      "event":"CONFIGURE",
      "lifecycle_events":[
        "server_configure.sh"
      ]
    },
    {
      "event":"INSTANTIATE",
      "lifecycle_events":[
        "install.sh"
      ]
    }
  ],
  "vdu":[
    {
      "vm_image":[
        ""
      ],
      "scale_in_out":1,
      "vnfc":[
        {
          "connection_point":[
            {              
              "virtual_link_reference":"private"
            }
          ]
        }
      ],
      "vimInstanceName":[]
    }
  ],
  "virtual_link":[
    {
      "name":"private"
    }
  ],
  "deployment_flavour":[
    {
      "flavour_key":"m1.small"
    }
  ],
  "type":"client",
  "endpoint":"generic",
  "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
}
```
</p></details>
<details>
  <summary>iperf-server</summary>
<p>

  ```JSON
{
  "name":"iperf-server",
  "vendor":"FOKUS",
  "version":"1.0",
  "lifecycle_event":[
    {
      "event":"INSTANTIATE",
      "lifecycle_events":[
        "install.sh",
        "install-srv.sh"
      ]
    }
  ],
  "virtual_link":[
    {
      "name":"private"
    }
  ],
  "vdu":[
    {
      "vm_image":[
      ],
      "scale_in_out":1,
      "vnfc":[
        {
          "connection_point":[
            {              
              "virtual_link_reference":"private",             
            }
          ]
        }
      ],
      "vimInstanceName":[]
    }
  ],
  "deployment_flavour":[
    {
      "flavour_key":"m1.small"
    }
  ],
  "type":"server",
  "endpoint":"generic",
  "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
}
```
</p></details>

<details>
  <summary>tutorial-iperf-NSR-privateIPs.json</summary>
  <p>

```JSON
{
  "name":"NSD iperf + privateIPs",
  "vendor":"FOKUS",
  "version":"1.0",
  "vld":[
    {
      "name":"private"
    }
  ],
  "vnfd":[
    {
      "name":"iperf-client",
      "vendor":"FOKUS",
      "version":"1.0",
      "lifecycle_event":[
        {
          "event":"CONFIGURE",
          "lifecycle_events":[
            "server_configure.sh"
          ]
        },
        {
          "event":"INSTANTIATE",
          "lifecycle_events":[
            "install.sh"
          ]
        }
      ],
      "vdu":[
        {
          "vm_image":[
            "iperf_client_image"
          ],
          "scale_in_out":1,
          "vnfc":[
            {
              "connection_point":[
                {
                  "virtual_link_reference":"private",
                  "interfaceId":0
                }
              ]
            }
          ],
          "vimInstanceName":[]
        }
      ],
      "virtual_link":[
        {
          "name":"private"
        }
      ],
      "deployment_flavour":[
        {
          "flavour_key":"m1.small"
        }
      ],
      "type":"client",
      "endpoint":"generic",
      "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
    },
    {
      "name":"iperf-server",
      "vendor":"FOKUS",
      "version":"1.0",
      "lifecycle_event":[
        {
          "event":"INSTANTIATE",
          "lifecycle_events":[
            "install.sh",
            "install-srv.sh"
          ]
        }
      ],
      "virtual_link":[
        {
          "name":"private"
        }
      ],
      "vdu":[
        {
          "vm_image":[
            "iperf_server_image"
          ],
          "scale_in_out":1,
          "vnfc":[
            {
              "connection_point":[
                {
                  "virtual_link_reference":"private",
                  "interfaceId":0
                }
              ]
            }
          ],
          "vimInstanceName":[]
        }
      ],
      "deployment_flavour":[
        {
          "flavour_key":"m1.small"
        }
      ],
      "type":"server",
      "endpoint":"generic",
      "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
    }
  ],
  "vnf_dependency":[
    {
      "source":{
        "name":"iperf-server"
      },
      "target":{
        "name":"iperf-client"
      },
      "parameters":[
        "private"
      ]
    }
  ]
}
```
</p></details>

So, it is able to upload/create images, flavor, but faces problem with network.
Here are the logs:

<details>
  <summary>generic-vnfm.log</summary>
  <p>

```
2017-03-30 16:26:46.704 ERROR 683 --- [pool-4-thread-15] o.o.common.vnfm_sdk.AbstractVnfm         : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-8774813 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:46.704 ERROR 683 --- [SimpleAsyncTaskExecutor-5] o.o.common.vnfm_sdk.AbstractVnfm         : Got exception while allocating vms
2017-03-30 16:26:46.705 ERROR 683 --- [SimpleAsyncTaskExecutor-5] o.o.common.vnfm_sdk.AbstractVnfm         : ERROR: 

org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-8774813 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.allocateResources(AbstractVnfm.java:725)
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.call(AbstractVnfm.java:738)
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.call(AbstractVnfm.java:686)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

2017-03-30 16:26:46.705 DEBUG 683 --- [SimpleAsyncTaskExecutor-5] o.o.common.vnfm_sdk.AbstractVnfm         : sending VNFR with version: 2
2017-03-30 16:26:46.705 DEBUG 683 --- [SimpleAsyncTaskExecutor-5] o.o.c.v.amqp.VnfmSpringHelperRabbit      : Sending message to Queue:  vnfm.nfvo.actions
2017-03-30 16:26:51.278 ERROR 683 --- [pool-4-thread-2] o.o.common.vnfm_sdk.AbstractVnfm         : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-8031372 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:51.278 ERROR 683 --- [SimpleAsyncTaskExecutor-4] o.o.common.vnfm_sdk.AbstractVnfm         : Got exception while allocating vms
2017-03-30 16:26:51.279 ERROR 683 --- [SimpleAsyncTaskExecutor-4] o.o.common.vnfm_sdk.AbstractVnfm         : ERROR: 

org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-8031372 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.allocateResources(AbstractVnfm.java:725)
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.call(AbstractVnfm.java:738)
        at org.openbaton.common.vnfm_sdk.AbstractVnfm$AllocateResources.call(AbstractVnfm.java:686)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```  
</p></details>

<details>
  <summary>openbaton.log</summary>
  <p>

```
2017-03-30 16:26:39.476  INFO 17 --- [SimpleAsyncTaskExecutor-16] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Sent INSTANTIATE to VNF: iperf-server
2017-03-30 16:26:39.495  INFO 17 --- [SimpleAsyncTaskExecutor-16] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Sent INSTANTIATE to VNF: iperf-client
2017-03-30 16:26:39.544  INFO 17 --- [SimpleAsyncTaskExecutor-3] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task grantoperationTask for vnfr iperf-client. Cyclic=false
2017-03-30 16:26:39.544  INFO 17 --- [OpenbatonTask-5] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: GrantOperation on VNFR: iperf-client
2017-03-30 16:26:39.547  INFO 17 --- [SimpleAsyncTaskExecutor-4] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task grantoperationTask for vnfr iperf-server. Cyclic=false
2017-03-30 16:26:39.547  INFO 17 --- [OpenbatonTask-6] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: GrantOperation on VNFR: iperf-server
2017-03-30 16:26:39.739  INFO 17 --- [OpenbatonTask-6] o.o.n.c.c.VNFLifecycleOperationGranting  : Granting Lifecycle Operation for vnfr: iperf-server
2017-03-30 16:26:39.770  INFO 17 --- [OpenbatonTask-5] o.o.n.c.c.VNFLifecycleOperationGranting  : Granting Lifecycle Operation for vnfr: iperf-client
2017-03-30 16:26:40.199  INFO 17 --- [OpenbatonTask-5] org.openbaton.vim_impl.vim.OpenstackVIM  : Listed Quota successfully for Tenant admin of VimInstance Openstack -> Quota: Quota{id='null', version=0, tenant='admin', cores='20', floatingIps='10', instances='10', keypairs='100', ram='51200'}
2017-03-30 16:26:40.213  INFO 17 --- [OpenbatonTask-6] org.openbaton.vim_impl.vim.OpenstackVIM  : Listed Quota successfully for Tenant admin of VimInstance Openstack -> Quota: Quota{id='null', version=0, tenant='admin', cores='20', floatingIps='10', instances='10', keypairs='100', ram='51200'}
2017-03-30 16:26:43.516  INFO 17 --- [OpenbatonTask-6] o.o.n.c.c.VNFLifecycleOperationGranting  : Enough resources are available for deploying VDU in vimInstance: Openstack
2017-03-30 16:26:43.516  INFO 17 --- [OpenbatonTask-6] o.o.n.v.tasks.abstracts.AbstractTask     : VimInstances chosen are: 72205172-d555-45cd-91a6-50ba920f031f: Openstack
2017-03-30 16:26:43.517  INFO 17 --- [OpenbatonTask-6] o.o.n.v.tasks.abstracts.AbstractTask     : Finished task: GrantOperation on VNFR: iperf-server
2017-03-30 16:26:43.630  INFO 17 --- [SimpleAsyncTaskExecutor-2] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task allocateresourcesTask for vnfr iperf-server. Cyclic=false
2017-03-30 16:26:43.631  INFO 17 --- [OpenbatonTask-7] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: AllocateResources for VNFR: iperf-server
2017-03-30 16:26:43.652  INFO 17 --- [OpenbatonTask-5] o.o.n.c.c.VNFLifecycleOperationGranting  : Enough resources are available for deploying VDU in vimInstance: Openstack
2017-03-30 16:26:43.652  INFO 17 --- [OpenbatonTask-5] o.o.n.v.tasks.abstracts.AbstractTask     : VimInstances chosen are: 49f364df-b53a-418f-80f2-c2f1c73873ba: Openstack
2017-03-30 16:26:43.653  INFO 17 --- [OpenbatonTask-5] o.o.n.v.tasks.abstracts.AbstractTask     : Finished task: GrantOperation on VNFR: iperf-client
2017-03-30 16:26:43.661  INFO 17 --- [SimpleAsyncTaskExecutor-17] o.o.nfvo.core.core.ResourceManagement    : FloatingIp chosen are: {}
2017-03-30 16:26:43.662  INFO 17 --- [SimpleAsyncTaskExecutor-17] org.openbaton.vim_impl.vim.OpenstackVIM  : Image choosed with name: iperf_server_image and ExtId: 59308ebc-5112-4005-93d2-a5e7ea7e03a0
2017-03-30 16:26:43.662  INFO 17 --- [SimpleAsyncTaskExecutor-17] org.openbaton.vim_impl.vim.OpenstackVIM  : Found DeploymentFlavour with ExtId: deea76d1-088d-4531-be05-e60f7194c9a6 of DeploymentFlavour with name: m1.small on VimInstance Openstack
2017-03-30 16:26:43.762  INFO 17 --- [SimpleAsyncTaskExecutor-1] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task allocateresourcesTask for vnfr iperf-client. Cyclic=false
2017-03-30 16:26:43.762  INFO 17 --- [OpenbatonTask-8] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: AllocateResources for VNFR: iperf-client
2017-03-30 16:26:43.793  INFO 17 --- [SimpleAsyncTaskExecutor-18] o.o.nfvo.core.core.ResourceManagement    : FloatingIp chosen are: {}
2017-03-30 16:26:43.794  INFO 17 --- [SimpleAsyncTaskExecutor-18] org.openbaton.vim_impl.vim.OpenstackVIM  : Image choosed with name: iperf_client_image and ExtId: 807e8150-4183-4217-9f2b-36682e56b59d
2017-03-30 16:26:43.794  INFO 17 --- [SimpleAsyncTaskExecutor-18] org.openbaton.vim_impl.vim.OpenstackVIM  : Found DeploymentFlavour with ExtId: deea76d1-088d-4531-be05-e60f7194c9a6 of DeploymentFlavour with name: m1.small on VimInstance Openstack
2017-03-30 16:26:46.610 ERROR 17 --- [SimpleAsyncTaskExecutor-17] org.openbaton.vim_impl.vim.OpenstackVIM  : Not launched VM with hostname iperf-server-8774813 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:46.614 ERROR 17 --- [OpenbatonTask-7] o.o.n.v.tasks.abstracts.AbstractTask     : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-8774813 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:46.742  INFO 17 --- [SimpleAsyncTaskExecutor-4] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task errorTask for vnfr iperf-server. Cyclic=false
2017-03-30 16:26:46.743 ERROR 17 --- [OpenbatonTask-9] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-8774813 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:46.754 ERROR 17 --- [OpenbatonTask-9] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: iperf-server
2017-03-30 16:26:51.230 ERROR 17 --- [SimpleAsyncTaskExecutor-18] org.openbaton.vim_impl.vim.OpenstackVIM  : Not launched VM with hostname iperf-client-8031372 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:51.234 ERROR 17 --- [OpenbatonTask-8] o.o.n.v.tasks.abstracts.AbstractTask     : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-8031372 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:51.316  INFO 17 --- [SimpleAsyncTaskExecutor-5] org.openbaton.nfvo.vnfm_reg.VnfmManager  : Executing Task errorTask for vnfr iperf-client. Cyclic=false
2017-03-30 16:26:51.317 ERROR 17 --- [OpenbatonTask-10] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-8031372 successfully on VimInstance Openstack. Caused by: org.openbaton.exceptions.VimDriverException: Multiple possible networks found, use a Network ID to be more specific.
2017-03-30 16:26:51.324 ERROR 17 --- [OpenbatonTask-10] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: iperf-client
```
</p></details>

At the same time Open Baton created "private" network successfuly:
![private_net_created_by_openbaton](https://cloud.githubusercontent.com/assets/19220793/24548459/00bebdca-161e-11e7-9a77-ca6f1dcee151.png)

What need I to do to resolve this problem? Is "virtual_link_reference" the right place to specify Openstack network name? Is there a "networkId" or another key with which i can specify Openstack network ID?

**Comment by lorenzotomasini** [comment]
Hi @dtyunin ,

would be useful to check openstack4j-plugin logs. Anyway, for keeping on going i suggest to do the following:
1. refresh the vim from the viminstance page. Now you should be able to see network and subnet as stated. If not stop here and send us the openstack4j plugin logs.
2. redeploy the NS. This time should go through. please remember that the VMs needs internet access in order to download the scripts and the EMS.

Without the plugin log we cannot tell you more. Please let us know how it proceeds

**Comment by dtyunin** [comment]
Thank you for advice.
I refreshed viminstance page, but I see only 4 networks
![networks_drawed](https://cloud.githubusercontent.com/assets/19220793/24551469/42d4e65a-162b-11e7-870d-6c4b755a6e9e.png)
 while we are having 12 at the moment including freshly created "private" network.

Please, see plugin logs
[plugin.txt](https://github.com/openbaton/openstack4j-plugin/files/885745/plugin.txt)

**Comment by lorenzotomasini** [comment]
From the log of the plugin i am not able to see where you run the refresh of the plugin. Last operation is the launchInstance. 

When i say refresh the vimInstance i mean clicking on the two arrows on the specific vim instance page, like this:

<img width="516" alt="screen shot 2017-03-29 at 10 59 07" src="https://cloud.githubusercontent.com/assets/3480153/24552527/14a703c0-1627-11e7-92c1-e3090765883c.png">


sorry for being so punctilious but sometimes i am not clear

**Comment by dtyunin** [comment]
Sorry, it was "tailed" part. Here is full log
[plugin-openstack_2017-03-30_04-12-09.txt](https://github.com/openbaton/openstack4j-plugin/files/886206/plugin-openstack_2017-03-30_04-12-09.txt)

**Comment by dtyunin** [comment]
I installed Open Baton with this command
`sh <(curl -s http://get.openbaton.org/bootstrap) release`
Also, I chose the latest version everywhere and issue had been disappeared.
